### Find all Content
GET http://localhost:8080/api/content



### Get Content by ID
GET http://localhost:8080/api/content

### Create new Content
POST http://localhost:8080/api/content
Content-Type: application/json

{
  "id": 2,
  "title": "My second blog post",
  "desc": "my second blog post",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2023-08-29T22:55:55.6787924",
  "dateUpdated": null,
  "url": ""
}

### Update exisiting Content
PUT http://localhost:8080/api/content/1
Content-Type: application/json

{
  "id": 1,
  "title": "MY FIRST POST!!!",
  "desc": "FIRST BLOG POST",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2023-08-29T22:55:55.6787924",
  "dateUpdated": "2023-08-29T22:55:55.6787924",
  "url": "http://localhost:8080/my-first-blog-post"
}

### Update exisiting Content with invalid id
PUT http://localhost:8080/api/content/99
Content-Type: application/json

{
  "id": 1,
  "title": "MY FIRST POST!!!",
  "desc": "FIRST BLOG POST",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2023-08-29T22:55:55.6787924",
  "dateUpdated": "2023-08-29T22:55:55.6787924",
  "url": "http://localhost:8080/my-first-blog-post"
}

### Delete by id blog post
DELETE http://localhost:8080/api/content/2